import React, { useState, useEffect, useRef } from 'react';
import MirageShader from './components/MirageShader';
import { callAI } from './callAI';
import { exportChat } from './utils/export';
import { PROVIDERS } from './providers';
import { fetchProviderModels } from './modelFetcher';

// Premium SVG Icons (Generated by GLM)
const Icon = ({ path, className = "w-5 h-5" }) => <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" d={path}></path></svg>;
const IPlus = "M12 4v16m8-8H4";
const ISend = "M12 19l9 2-9-18-9 18 9-2zm0 0v-8";
const IMic = "M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z";
const ISearch = "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z";
const ICog = "M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z";
const IChat = "M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z";
const IGrid = "M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z";

export default function App() {
  const [input, setInput] = useState("");
  const [isDrawerOpen, setIsDrawerOpen] = useState(false);
  const [messages, setMessages] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const chatEndRef = useRef(null);

  // Dynamic Providers & Models
  const [provider, setProvider] = useState('openrouter');
  const [model, setModel] = useState('');
  const [apiKey, setApiKey] = useState(localStorage.getItem('mirage_api_key') || '');
  const [fetchedModels, setFetchedModels] = useState([]);
  const [loadingModels, setLoadingModels] = useState(false);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  // 1. Fetch Models dynamically when API Key or Provider changes
  useEffect(() => {
    const fetchModels = async () => {
      if (!apiKey) { setFetchedModels([]); return; }
      setLoadingModels(true);
      const models = await fetchProviderModels(provider, apiKey);
      setFetchedModels(models);
      if (models.length > 0 && !model) setModel(models[0].id);
      setLoadingModels(false);
    };
    fetchModels();
  }, [apiKey, provider]);

  // 2. Send Message Logic
  const sendMessage = async () => {
    if (!input.trim() || !apiKey) return alert('Enter an API Key first');
    const userMsg = { role: 'user', content: input };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setInput('');
    setIsLoading(true);

    try {
      const reply = await callAI({ messages: newMessages, model, provider, apiKey });
      setMessages([...newMessages, { role: 'assistant', content: reply }]);
      speakText(reply);
    } catch (err) {
      setMessages([...newMessages, { role: 'assistant', content: `Error: ${err.message}` }]);
    } finally {
      setIsLoading(false);
    }
  };

  // 3. TTS & STT
  const speakText = (text) => {
    if (!window.speechSynthesis) return;
    window.speechSynthesis.cancel();
    const utterance = new SpeechSynthesisUtterance(text);
    utterance.rate = 1.0; utterance.pitch = 1.0;
    window.speechSynthesis.speak(utterance);
  };

  const toggleListening = () => {
    if (!('webkitSpeechRecognition' in window || 'SpeechRecognition' in window)) {
      return alert("Speech recognition not supported in this browser.");
    }
    if (isListening) { recognition.stop(); setIsListening(false); return; }
    
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    const recognition = new SpeechRecognition();
    recognition.lang = 'en-US'; recognition.interimResults = true; recognition.continuous = false;
    recognition.onresult = (event) => {
      const transcript = Array.from(event.results).map(result => result[0].transcript).join('');
      setInput(transcript);
    };
    recognition.onend = () => setIsListening(false);
    recognition.start(); setIsListening(true);
    recognition.onerror = () => setIsListening(false);
  };

  // 4. Split Models by Price
  const freeModels = fetchedModels.filter(m => m.free || m.pricePrompt === 0);
  const paidModels = fetchedModels.filter(m => !m.free && m.pricePrompt > 0);

  // Mock Sidebar Contacts (Kept for aesthetics)
  const contacts = [
    { name: "Mirage Ultra", status: "Active", color: "#D4AF37" },
    { name: "Mind Spa PRO+", status: "Online", color: "#3B82F6" },
    { name: "Arounda Dev", status: "Online", color: "#8B5CF6" },
    { name: "Archiver Bot", status: "Offline", color: "#6B7280" }
  ];

  const vibrantActions = [
    { label: "White Label", color: "red", icon: "M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" },
    { label: "Prod", color: "orange", icon: "M13 10V3L4 14h7v7l9-11h-7z" },
    { label: "Business", color: "green", icon: "M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" },
    { label: "Tech", color: "purple", icon: "M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" }
  ];

  return (
    <div className="relative w-full h-screen flex overflow-hidden font-sans">
      <MirageShader />
      
      {/* Ambient Color Blobs */}
      <div className="absolute top-1/4 left-1/4 w-[600px] h-[600px] bg-blue-600 opacity-[0.05] rounded-full blur-[150px] pointer-events-none"></div>
      <div className="absolute bottom-1/4 right-1/4 w-[500px] h-[500px] bg-red-600 opacity-[0.05] rounded-full blur-[150px] pointer-events-none"></div>

      {/* 1. Left Sidebar (Command Center) */}
      <aside className="w-72 h-full flex flex-col gap-4 p-4 z-20 border-r border-white/5 bg-black/20 backdrop-blur-2xl">
        
        <div className="animate-slide-in-left mt-2 mb-4">
          <h1 className="text-2xl font-bold tracking-tight text-mirage-gradient">MIRAGE</h1>
          <p className="text-xs text-[#A1A5AB] font-light tracking-widest uppercase mt-1">Chat Smarter, Not Harder</p>
        </div>

        <div className="relative animate-slide-in-left delay-75">
          <div className="absolute left-3 top-1/2 -translate-y-1/2 text-[#A1A5AB]">
            <Icon path={ISearch} className="w-4 h-4" />
          </div>
          <input 
            placeholder="Search..." 
            className="w-full bg-white/5 border border-white/10 rounded-xl pl-9 pr-3 py-2.5 text-sm text-[#F5F5F7] placeholder-[#A1A5AB] outline-none focus:border-[#D4AF37]/30 focus:bg-black/20 transition-all font-light"
          />
        </div>

        <div className="flex-1 overflow-y-auto -mr-2 pr-2 flex flex-col gap-2 mt-2">
          <span className="text-xs text-[#A1A5AB]/50 px-2 mb-1 font-medium tracking-wider uppercase">Agents</span>
          {contacts.map((c, i) => (
            <div 
              key={i} 
              className={`flex items-center gap-3 p-2 rounded-xl cursor-pointer transition-all duration-300 ${i === 0 ? 'bg-gradient-to-r from-white/10 to-transparent border-l-2 border-[#D4AF37]' : 'hover:bg-white/5'}`}
            >
              <div className="relative">
                <div className="w-9 h-9 rounded-full bg-gradient-to-br from-[#2C2E33] to-[#121316] border border-white/10 flex items-center justify-center text-xs font-bold text-[#F5F5F7]">
                  {c.name[0]}
                </div>
                <div className="absolute bottom-0 right-0 w-2.5 h-2.5 rounded-full border-2 border-[#0d0e10]" style={{ backgroundColor: c.color }}></div>
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium text-[#F5F5F7] truncate">{c.name}</p>
                <p className="text-xs text-[#A1A5AB] truncate">{c.status}</p>
              </div>
            </div>
          ))}
        </div>

        <div className="flex justify-around p-2 bg-black/30 rounded-2xl border border-white/5 backdrop-blur-xl">
          <button className="p-3 rounded-xl text-[#D4AF37] bg-white/5 hover:bg-white/10 transition-colors"><Icon path={IChat} /></button>
          <button className="p-3 rounded-xl text-[#A1A5AB] hover:text-[#F5F5F7] hover:bg-white/5 transition-colors"><Icon path={IGrid} /></button>
          <button className="p-3 rounded-xl text-[#A1A5AB] hover:text-[#F5F5F7] hover:bg-white/5 transition-colors"><Icon path={ICog} /></button>
        </div>
      </aside>

      {/* 2. Main Chat Area */}
      <main className="flex-1 flex flex-col h-full relative z-10">
        
        {/* Top Floating Bar (Fused with Dynamic Dropdowns) */}
        <header className="absolute top-4 left-4 right-4 z-30 flex justify-between items-center p-3 pl-5 rounded-2xl bg-[#1A1D21]/40 backdrop-blur-2xl border border-white/10 shadow-[0_8px_32px_rgba(0,0,0,0.4)]">
          <div className="flex items-center gap-4">
            <div className="w-8 h-8 rounded-full bg-gradient-to-br from-[#D4AF37] to-[#8a6d1e] flex items-center justify-center text-xs font-bold text-black">M</div>
            
            {/* Provider Selector */}
            <div className="flex items-center gap-2 bg-white/5 rounded-full px-3 py-1 border border-white/10">
              <select 
                value={provider} 
                onChange={(e) => setProvider(e.target.value)}
                className="bg-transparent text-xs text-[#F5F5F7] outline-none cursor-pointer"
              >
                {Object.entries(PROVIDERS).map(([key, p]) => (
                  <option key={key} value={key} className="bg-[#121316]">{p.name}</option>
                ))}
              </select>
            </div>

            {/* Model Selector */}
            <div className="relative flex items-center gap-2 bg-white/5 rounded-full px-3 py-1 border border-white/10">
              <span className={`w-1.5 h-1.5 rounded-full ${loadingModels ? 'bg-[#A1A5AB] animate-pulse' : 'bg-[#D4AF37]'}`}></span>
              <select 
                value={model} 
                onChange={(e) => setModel(e.target.value)}
                className="bg-transparent text-xs text-[#A1A5AB] outline-none cursor-pointer w-32"
              >
                {loadingModels && <option className="bg-[#121316]">Loading...</option>}
                {freeModels.length > 0 && <optgroup label="🆓 Free" className="bg-[#121316]">
                  {freeModels.map(m => <option key={m.id} value={m.id} className="bg-[#121316]">{m.name}</option>)}
                </optgroup>}
                {paidModels.length > 0 && <optgroup label="💎 Paid" className="bg-[#121316]">
                  {paidModels.map(m => <option key={m.id} value={m.id} className="bg-[#121316]">{m.name}</option>)}
                </optgroup>}
              </select>
            </div>
          </div>
          
          <div className="flex items-center gap-3">
            {/* API Key Input (Replaces Upgrade PRO+ button) */}
            <input 
              type="password"
              value={apiKey}
              onChange={(e) => { setApiKey(e.target.value); localStorage.setItem('mirage_api_key', e.target.value); }}
              placeholder="API Key..."
              className="w-28 md:w-36 bg-black/20 text-xs text-[#F5F5F7] placeholder-[#A1A5AB]/50 px-3 py-1.5 rounded-full outline-none focus:ring-1 focus:ring-[#D4AF37]/50 transition-all font-light"
            />
            <button className="text-xs text-[#F5F5F7] bg-white/5 hover:bg-white/10 px-4 py-2 rounded-full border border-white/10 transition-all">Share</button>
          </div>
        </header>

        {/* Chat Stream */}
        <div className="flex-1 overflow-y-auto pt-24 pb-44 px-4 md:px-8 flex flex-col gap-6">
          {messages.length === 0 && (
             <div className="flex-1 flex flex-col items-center justify-center text-[#A1A5AB] text-xs font-light tracking-widest uppercase opacity-50">
               <div className="mb-4 w-12 h-12 rounded-full border border-white/10 bg-white/5 flex items-center justify-center">M</div>
               Ready to assist.
             </div>
          )}
          {messages.map((msg, index) => (
            <div 
              key={index} 
              className={`flex animate-fade-in-up ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
              style={{ animationDelay: `${index * 0.1}s` }}
            >
              <div className={`max-w-[75%] ${msg.role === 'user' ? 'items-end' : 'items-start'}`}>
                <div className={`p-4 rounded-3xl shadow-[0_8px_32px_rgba(0,0,0,0.3)] ${
                    msg.role === 'user' 
                      ? 'bg-gradient-to-br from-[#E4E6EB] to-[#A1A5AB] text-black rounded-br-md font-medium' 
                      : 'bg-[#1A1D21]/60 backdrop-blur-xl border border-white/10 border-l-2 border-l-[#D4AF37] text-[#F5F5F7] rounded-bl-md'
                  }`}>
                  <p className="text-sm leading-relaxed tracking-wide font-light">{msg.content}</p>
                </div>
              </div>
            </div>
          ))}
          {isLoading && (
            <div className="flex justify-start animate-fade-in-up">
              <div className="max-w-[75%] p-4 rounded-3xl bg-[#1A1D21]/60 backdrop-blur-xl border border-white/10 border-l-2 border-l-[#D4AF37] text-[#A1A5AB] rounded-bl-md">
                <p className="text-sm font-light tracking-wide">Mirage is thinking...</p>
              </div>
            </div>
          )}
          <div ref={chatEndRef} />
        </div>

        {/* 3. Composer & Drawer Area */}
        <footer className="absolute bottom-6 left-1/2 -translate-x-1/2 w-[95%] max-w-3xl z-30 flex flex-col items-center">
          
          {/* Vibrant Tech Drawer */}
          {isDrawerOpen && (
            <div className="w-full mb-4 animate-scale-in-drawer origin-bottom">
              <div className="p-4 rounded-3xl bg-[#1A1D21]/60 backdrop-blur-2xl border border-white/10 shadow-[0_8px_32px_rgba(0,0,0,0.6)] flex flex-col gap-4">
                
                <div className="grid grid-cols-4 gap-3">
                  {vibrantActions.map((action, i) => (
                    <button 
                      key={i}
                      className={`group flex flex-col items-center justify-center gap-2 p-4 rounded-2xl bg-black/30 border border-white/5 transition-all duration-300 hover:scale-105 hover:border-white/10 glow-${action.color}`}
                    >
                      <div className={`w-10 h-10 rounded-xl flex items-center justify-center bg-gradient-to-b ${
                        action.color === 'red' ? 'from-red-500 to-red-700' :
                        action.color === 'orange' ? 'from-orange-500 to-orange-700' :
                        action.color === 'green' ? 'from-green-500 to-green-700' :
                        'from-purple-500 to-purple-700'
                      } group-hover:scale-110 transition-transform`}>
                        <Icon path={action.icon} className="w-5 h-5 text-white" />
                      </div>
                      <span className="text-xs font-medium text-[#A1A5AB] group-hover:text-white transition-colors">{action.label}</span>
                    </button>
                  ))}
                </div>

                <div className="h-px bg-white/5"></div>

                {/* Standard Tools (Now Functioning) */}
                <div className="flex justify-around">
                  <button onClick={toggleListening} className={`flex items-center gap-2 px-4 py-2 rounded-full text-xs font-medium transition-all hover:bg-white/5 ${isListening ? 'text-red-400' : 'text-[#A1A5AB] hover:text-[#F5F5F7]'}`}>
                    <Icon path={IMic} className="w-4 h-4" /> {isListening ? 'Stop' : 'Voice'}
                  </button>
                  <button onClick={() => speakText(messages[messages.length - 1]?.content || '')} className="flex items-center gap-2 px-4 py-2 rounded-full text-[#A1A5AB] hover:text-[#F5F5F7] text-xs font-medium transition-all hover:bg-white/5">
                    <Icon path="M11 5L6 9H2v6h4l5 4V5z" className="w-4 h-4" /> TTS
                  </button>
                  <button onClick={() => exportChat(messages, 'json')} className="flex items-center gap-2 px-4 py-2 rounded-full text-[#A1A5AB] hover:text-[#F5F5F7] text-xs font-medium transition-all hover:bg-white/5">
                    <Icon path="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" className="w-4 h-4" /> Export
                  </button>
                </div>
              </div>
            </div>
          )}

          {/* Composer Pill */}
          <div className="w-full group">
            <div className="flex items-center gap-3 p-2 pl-2 pr-2 rounded-full bg-[#1A1D21]/40 backdrop-blur-2xl border border-white/10 shadow-[0_8px_32px_rgba(0,0,0,0.6)] transition-all duration-300 group-focus-within:scale-[1.01] group-focus-within:border-[#D4AF37]/30">
              
              <button 
                onClick={() => setIsDrawerOpen(!isDrawerOpen)}
                className={`flex-shrink-0 flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-b from-[#2C2E33] to-[#121316] border border-white/10 hover:border-[#D4AF37]/40 transition-all duration-300 active:scale-90 ${isDrawerOpen ? 'rotate-45 bg-gradient-to-b from-[#D4AF37] to-[#8a6d1e] text-black' : 'text-[#F5F5F7]'}`}
              >
                <Icon path={IPlus} />
              </button>

              <input 
                type="text"
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && sendMessage()}
                placeholder="Message Mirage Ultra..."
                className="flex-1 w-full bg-transparent outline-none text-[#F5F5F7] placeholder-[#A1A5AB] text-sm font-light tracking-wide px-1"
              />

              <button onClick={sendMessage} className="flex-shrink-0 flex items-center justify-center w-10 h-10 rounded-full bg-gradient-to-b from-[#E4E6EB] to-[#A1A5AB] hover:from-[#F5F5F7] hover:to-[#E4E6EB] transition-all duration-300 shadow-[0_4px_12px_rgba(0,0,0,0.4)] active:scale-90 glow-gold">
                <Icon path={ISend} className="w-5 h-5 text-[#121316]" />
              </button>
            </div>
          </div>
        </footer>

      </main>
    </div>
  );
}
