export const PROVIDERS = [
  {
    id: 'openrouter',
    name: 'OpenRouter',
    color: '#8b1a4a',
    modelsEndpoint: 'https://openrouter.ai/api/v1/models',
    requiresKey: false,
    isFree: true,
    description: '200+ models, one key',
  },
  {
    id: 'groq',
    name: 'Groq',
    color: '#f55036',
    modelsEndpoint: 'https://api.groq.com/openai/v1/models',
    requiresKey: true,
    isFree: true,
    description: 'Ultra-fast inference',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    color: '#4285f4',
    modelsEndpoint: 'https://generativelanguage.googleapis.com/v1beta/models',
    requiresKey: true,
    isFree: true,
    description: 'Google AI models',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    color: '#d4a27e',
    modelsEndpoint: null,
    requiresKey: true,
    isFree: false,
    description: 'Claude models',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    color: '#4d9fff',
    modelsEndpoint: 'https://api.deepseek.com/models',
    requiresKey: true,
    isFree: true,
    description: 'Reasoning models',
  },
  {
    id: 'mistral',
    name: 'Mistral',
    color: '#ff7000',
    modelsEndpoint: 'https://api.mistral.ai/v1/models',
    requiresKey: true,
    isFree: false,
    description: 'European AI models',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    color: '#39594d',
    modelsEndpoint: 'https://api.cohere.com/v1/models',
    requiresKey: true,
    isFree: false,
    description: 'Enterprise NLP',
  },
  {
    id: 'together',
    name: 'Together AI',
    color: '#7c3aed',
    modelsEndpoint: 'https://api.together.xyz/v1/models',
    requiresKey: true,
    isFree: false,
    description: 'Open source models',
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    color: '#06b6d4',
    modelsEndpoint: 'https://api.siliconflow.cn/v1/models',
    requiresKey: true,
    isFree: true,
    description: 'Free Chinese models',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    color: '#ffffff',
    modelsEndpoint: 'http://localhost:11434/api/tags',
    requiresKey: false,
    isFree: true,
    description: 'Local models',
  },
]

export const getProvider = (id) => PROVIDERS.find(p => p.id === id)
